### ISSUE TITLE
Milestone 1 feeback

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/survey_arrival_time#12]
Great job on this milestone!

- I was wondering if maybe another confounder would be whether people in general are the type of person who likes to be on time or not. I would imagine that someone who is very worried about being on time would arrive early regardless of how far they lived. While I know people who are always late even if its going right next to their house.

**Comment by milicmil** [comment]
We had a discussion about this and we did not think that one's perception of whether one likes to be on time or not is a confounder.  We have two objections with this notion. 

Firstly, I would say that one would not actively like to not be on time. I am not sure in which cases that would be true especially in a work or school setting where the expectation is to be on time. I for example like to be on time, but I am generally 3 to 5 min late for class. 

Secondly, one's desire on whether one likes to be late does not influence one's arrival time. I also does not influences one's distance from the classroom which is something a confounder would be affecting.
